### ISSUE TITLE
Not able to update 'Incidents' in v0.2

### ISSUE THREAD

**Issue by Srthk** [DivineOmega/cachet.php#36] opened 2016-06-16 07:17 UTC
```
use \DivineOmega\CachetPHP\Factories\CachetInstanceFactory;

$cachetInstance = CachetInstanceFactory::create($host, $token);

$incidents = $cachetInstance->getAllIncidents();
$incident = $incidents[0];
$incident->status = 1;
$incident->save();
```

Receiving the following error -

```
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `PUT http://status1.test.in/api/v1/incidents/2?name=Downtime%20Incoming%20Calls&message=%23%20Issue%20Observed%0D%0A%0D%0A%23%20Issue%20Fixed%20at%2012%3A15PM&status=1&visible=1&component_id=9` resulted in a `400 Bad Request` response:
{"errors":[{"id":"390e83d4-a2db-440f-b93d-2f0b4bb754cd","status":400,"title":"Bad Request","detail":"The request cannot  (truncated...)
' in /home/test/commonix/extlib/cachet-status-board-php-client/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
Stack trace:
#0 /home/test/commonix/extlib/cachet-status-board-php-client/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/test/commonix/extlib/cachet-status-board-php-client/vendor/guzzlehttp/promises/src/Promise.php(201): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /hom in /home/test/commonix/extlib/cachet-status-board-php-client/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 107

```

What is the fix for this?

**Comment by Jord-JD** [comment] 2016-06-17 08:51
Hi.

Just took a look into this. The truncated `Bad Request` you are getting is probably:

``` json
{
    "errors": [
        {
            "id": "1c2fc534-9e21-427c-8682-b8db7901b60d",
            "status": 400,
            "title": "Bad Request",
            "detail": "The request cannot be fulfilled due to bad syntax.",
            "meta": {
                "details": [
                    "The status format is invalid."
                ]
            }
        }
    ]
}
```

This is pretty strange, as the Cachet documentation says the status should be an integer when updating an incident. In fact, using the try it out form on the documentation page also fails with the same error. See here: https://docs.cachethq.io/docs/update-an-incident

So it looks like you're doing everything correctly. 

@jbrooksuk Have we stumbled upon an Cachet API bug or a bit of outdated documentation?

**Comment by jbrooksuk** [comment] 2016-06-17 08:57
I'm pretty sure this is fixed in the RC releases of 2.3 :)

**Comment by Jord-JD** [comment] 2016-06-17 08:57
For future reference, you can get the full un-truncated messages by surrounding your code segment with a try catch block similar to what's below.

``` php
try {
  $incident->status = 1;
  $incident->save();
} catch (Exception $e) {
  // Output full response body contents
  var_dump($e->getResponse()->getBody()->getContents());
}
```

**Comment by Jord-JD** [comment] 2016-06-17 08:58
Thanks for checking this out @jbrooksuk.

**Comment by Srthk** [comment] 2016-06-27 06:33
I'm still on v2.1.2 of Cachet, I haven't tried any RC release of 2.3. But ideally, it should still work as I'm able to achieve the same using cURL.

**Comment by jbrooksuk** [comment] 2016-06-27 07:55
> I'm still on v2.1.2 of Cachet, I haven't tried any RC release of 2.3. But ideally, it should still work as I'm able to achieve the same using cURL.

The bug is in Cachet though, so how are you able to do it in cURL?

**Comment by Srthk** [comment] 2016-06-27 08:13
cURL is working fine for me. I'm running something like this -

``` php
$data = array('id' => 2, 'status' => 3, 'message' => 'hello world');

$url = "status.xyz.com/api/v1/incidents";
$url .= "/" . $data['id'];
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'X-Cachet-Token: ' . $token
    ));
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
$response = curl_exec($ch);
```

**Comment by jbrooksuk** [comment] 2016-06-27 08:18
@DivineOmega https://github.com/DivineOmega/cachet.php/blob/master/src/Models/Incident.php you're missing the component status field from here?

**Comment by Jord-JD** [comment] 2016-06-27 15:25
@jbrooksuk You're looking at the master branch there. This issue refers to v0.2 (tagged).

**Comment by Jord-JD** [comment] 2016-06-29 15:06
@Srthk Cachet 2.3 is out now. Is the issue still present with the latest version of Cachet?

**Comment by Jord-JD** [comment] 2016-09-16 22:17
@Srthk Did you manage to solve this issue in the end?

**Comment by jbrooksuk** [comment] 2016-09-21 17:06
@DivineOmega the issue is fixed in Cachet, so this should no longer be a problem.

**Comment by Srthk** [comment] 2016-09-24 09:10
Hi. I haven't tried it out. But shouldn't be a problem I guess.

**Closed as completed** 2017-07-18 15:54 UTC
